fastai_config = """language: "en"  
pipeline: 
- name: "SpacyNLP" 
- name: "SpacyTokenizer" 
- name: "SpacyFeaturizer" 
- name: "RegexFeaturizer" 
- name: "CRFEntityExtractor" 
- name: "FastaiClassifier"    

policies:   
- name: MemoizationPolicy   
- name: KerasPolicy   
- name: MappingPolicy"""